import type { NextPage } from 'next';
import Head from 'next/head'; 
import Link from 'next/link';
import { useRouter } from 'next/router';

const App: NextPage = () => {
  const router = useRouter()
  console.log(router)
  return (
    <>
      <Head>
        <title>Interio App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Link href={'/'} className='text-primary bg-dark' >to go home</Link>
      <h1 className='text-3xl font-bold underline'>from app</h1>
    </>
  );
};

export default App;
